---

- name: Configure localhost as admin-workstation
  hosts: localhost
  gather_facts: false
  become: true

  tasks:

  - name: Get kubectl
    get_url:
      url: https://storage.googleapis.com/kubernetes-release/release/v{{ k8s_version }}/bin/linux/amd64/kubectl
      dest: /usr/local/bin/kubectl
      owner: root
      group: root
      mode: '0755'

