- hosts: k8sadmin
  gather_facts: false
  become: true
  tasks:

  - name: Checking if helm is installed
    stat:
      path: /usr/local/bin/helm
    register: helm_check
    ignore_errors: yes
    changed_when: False

  - name: Install helm
    shell: |
      curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
      chmod 700 get_helm.sh
      ./get_helm.sh
    args:
      executable: /bin/bash
    when: not helm_check.stat.exists
