---

- hosts: k8smaster
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw
      changed_when: false

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: k8sworkers
  become: yes
  tasks:
    - name: join cluster
      environment:
        JOIN_CMD: "{{ hostvars[groups['k8smaster'][0]].join_command }}"
      shell: |
        cd $HOME
        $JOIN_CMD >> node_joined.txt
      args:
        creates: node_joined.txt
